/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sv.edu.udb.proyecto.view;

import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import sv.edu.udb.proyecto.Sesion;
import sv.edu.udb.proyecto.dao.exception.DAOException;
import sv.edu.udb.proyecto.modelo.Departamento;
import sv.edu.udb.proyecto.modelo.Incidente;

/**
 *
 * @author josed
 */
public class IfrmTodosIncidentes extends javax.swing.JInternalFrame {
    public static boolean activo;
    DefaultTableModel dtm;
        private static SimpleDateFormat formato = new SimpleDateFormat("dd/MM/YYYY");

    /**
     * Creates new form ifrmTodosIncidentes
     */
    public IfrmTodosIncidentes() {
        initComponents();
        activo=true;
        cargarTabla();
    }

    private void cargarTabla() {
        Object[][] datos = {};
        String[] columnNames = Incidente.HEADERS;
        dtm = new DefaultTableModel(datos, columnNames);
        try {
                      
            Sesion.getDatos().getIncidenteDAO().obtenerTodos().forEach(proyecto -> {
                dtm.addRow(convertir(proyecto.getData()));
            });
        } catch (SQLException | ClassNotFoundException | DAOException ex) {
            Logger.getLogger(IfrmProyecto.class.getName()).log(Level.SEVERE, null, ex);
        }
        jtblIncidentes.setModel(dtm);

    }
    
    private Object[] convertir(Object[] fila) {
        try {
            fila[3] = ((((int) fila[3]) != 0)) ? Sesion.getDatos().getUsuarioDAO().obtener((int) fila[3]).getNombre() : "No asignado";
            fila[4] = ((((int) fila[4]) != 0)) ? Sesion.getDatos().getUsuarioDAO().obtener((int) fila[4]).getNombre() : "No asignado";
            fila[5] = formato.format((Date) fila[5]);
            fila[6] = Sesion.getDatos().getIncidenteDAO().estadoString((int) fila[6]);
            fila[7] = Sesion.getDatos().getProyectoDAO().obtener((int) fila[7]).getNombre();
        } catch (SQLException | ClassNotFoundException | DAOException ex) {
            Logger.getLogger(IfrmAprobar.class.getName()).log(Level.SEVERE, null, ex);
        }
        return fila;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtblIncidentes = new javax.swing.JTable();

        setClosable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                cerrar(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        jtblIncidentes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtblIncidentes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtblIncidentesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtblIncidentes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 726, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 702, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 324, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtblIncidentesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtblIncidentesMouseClicked
       
       
    }//GEN-LAST:event_jtblIncidentesMouseClicked

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked

    }//GEN-LAST:event_jScrollPane1MouseClicked

    private void cerrar(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_cerrar
        activo=false;        // TODO add your handling code here:
    }//GEN-LAST:event_cerrar


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtblIncidentes;
    // End of variables declaration//GEN-END:variables
}
