/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sv.edu.udb.proyecto.view;

import java.sql.SQLException;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import sv.edu.udb.proyecto.Sesion;
import sv.edu.udb.proyecto.dao.exception.DAOException;
import sv.edu.udb.proyecto.modelo.Departamento;
import sv.edu.udb.proyecto.modelo.Incidente;

/**
 *
 * @author josed
 */
public class IfrmProbar extends javax.swing.JInternalFrame {

    /**
     * Creates new form IfrmProbar
     */
    public static boolean activo;
    DefaultTableModel dtm;
    private Incidente incidenteActivo;
    
    public IfrmProbar() {
        activo=true;
        initComponents();
        cargarTabla();
    }

    private void cargarTabla() {
        Object[][] datos = {};
        String[] columnNames = {"CODIGO", "Nombre", "Descripción", "Detalle del caso"};
        dtm = new DefaultTableModel(datos, columnNames);
        try {
            Departamento dep = Sesion.getDatos().getDepartamentoDAO().obtener(Sesion.getUsuario().getDepartamentoId());
            Sesion.getDatos().getIncidenteDAO().incidentesByDepartamentoAndEstado(dep, 5)
                    .stream().filter(inc -> inc.getProbador()== Sesion.getUsuario().getId()).forEach(proyecto -> {
                dtm.addRow(transformar(proyecto));
            });
        } catch (SQLException | ClassNotFoundException | DAOException ex) {
            Logger.getLogger(IfrmBitacora.class.getName()).log(Level.SEVERE, null, ex);
        }
        jtblIncidentes.setModel(dtm);
    }
    
    private Object[] transformar(Incidente incidente) {
        Object[] fila = {
            incidente.getCodigo(),
            incidente.getNombre(),
            incidente.getDescripcion(),
            incidente.getDetalleCaso()
        };
        return fila;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtblIncidentes = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDetalle = new javax.swing.JTextArea();
        txtCodigo = new javax.swing.JTextField();
        btnAprobar = new javax.swing.JButton();
        btnDevolver = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();

        jtblIncidentes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtblIncidentes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtblIncidentesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtblIncidentes);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Codigo:");

        jLabel2.setText("Detalle");

        txtDetalle.setColumns(20);
        txtDetalle.setRows(5);
        jScrollPane2.setViewportView(txtDetalle);

        txtCodigo.setEditable(false);

        btnAprobar.setText("Aprobar");
        btnAprobar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAprobarActionPerformed(evt);
            }
        });

        btnDevolver.setText("Devolver");
        btnDevolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDevolverActionPerformed(evt);
            }
        });

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnAprobar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnDevolver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCerrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAprobar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDevolver, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtblIncidentesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtblIncidentesMouseClicked
        int fila = jtblIncidentes.rowAtPoint(evt.getPoint());
        int columna = jtblIncidentes.columnAtPoint(evt.getPoint());
        if ((fila > -1) && (columna > -1)) {
            try {
                incidenteActivo = Sesion.getDatos().getIncidenteDAO().obtenerTodos().stream().filter(inc -> {
                    if (inc.getCodigo() == null) {
                        return false;
                    }
                    return inc.getCodigo().equals((String) dtm.getValueAt(fila, 0));
                }).findFirst().orElse(null);
                txtCodigo.setText(incidenteActivo.getCodigo());
                txtDetalle.setText(incidenteActivo.getDescripcion());
            } catch (SQLException | ClassNotFoundException | DAOException ex) {
                Logger.getLogger(IfrmAprobar.class.getName()).log(Level.SEVERE, null, ex);
            }
        }  
    }//GEN-LAST:event_jtblIncidentesMouseClicked

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        activo = false;
        this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnAprobarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAprobarActionPerformed

        try {
            incidenteActivo.setEstado(6);
            Sesion.getDatos().getIncidenteDAO().modificar(incidenteActivo);
            limpiar();
            JOptionPane.showMessageDialog(null, "Incidente aprobado");
            cargarTabla();
        } catch (DAOException | SQLException | ClassNotFoundException ex) {
            System.out.println(ex);
            JOptionPane.showMessageDialog(null, "No se pudo cambiar el estado");
            Logger.getLogger(IfrmProbar.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAprobarActionPerformed

    private void btnDevolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDevolverActionPerformed
  try {
            incidenteActivo.setEstado(7);
            Calendar c = Calendar.getInstance();
            c.setTime(incidenteActivo.getFechaEntrega());
            c.add(Calendar.DATE, 7);  
            incidenteActivo.setFechaEntrega(c.getTime());
            Sesion.getDatos().getIncidenteDAO().modificar(incidenteActivo);
            limpiar();
            JOptionPane.showMessageDialog(null, "Incidente devuelto");
            cargarTabla();

        } catch (DAOException | SQLException | ClassNotFoundException ex) {
            System.out.println(ex);
            JOptionPane.showMessageDialog(null, "No se pudo cambiar el estado");
            Logger.getLogger(IfrmProbar.class.getName()).log(Level.SEVERE, null, ex);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnDevolverActionPerformed

    private void limpiar(){
        incidenteActivo= null;
        txtCodigo.setText("");
        txtDetalle.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAprobar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnDevolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jtblIncidentes;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextArea txtDetalle;
    // End of variables declaration//GEN-END:variables
}
