/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sv.edu.udb.proyecto.view;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.stream.Collectors;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import sv.edu.udb.proyecto.Sesion;
import sv.edu.udb.proyecto.dao.exception.DAOException;
import sv.edu.udb.proyecto.modelo.Bitacora;
import sv.edu.udb.proyecto.modelo.Departamento;
import sv.edu.udb.proyecto.modelo.Incidente;
import sv.edu.udb.proyecto.utils.BitacoraListModel;

/**
 *
 * @author josed
 */
public class IfrmBitacora extends javax.swing.JInternalFrame {

    /**
     * Creates new form IfrmBitacora
     */
    public static boolean activo;
    DefaultTableModel dtm;
    private Incidente incidenteActivo;
    private List<Bitacora> bitacoras;

    public IfrmBitacora() {
        initComponents();
        cargarTabla();
    }

    private void cargarTabla() {
        Object[][] datos = {};
        String[] columnNames = {"CODIGO", "Nombre", "Descripción", "Detalle del caso"};
        dtm = new DefaultTableModel(datos, columnNames);
        try {
            Departamento dep = Sesion.getDatos().getDepartamentoDAO().obtener(Sesion.getUsuario().getDepartamentoId());
            Sesion.getDatos().getIncidenteDAO().incidentesByDepartamentoAndEstado(dep, 2)
                    .stream().filter(inc -> inc.getDesarrollador() == Sesion.getUsuario().getId()).forEach(proyecto -> {
                dtm.addRow(transformar(proyecto));
            });
        } catch (SQLException | ClassNotFoundException | DAOException ex) {
            Logger.getLogger(IfrmBitacora.class.getName()).log(Level.SEVERE, null, ex);
        }
        jtblIncidentes.setModel(dtm);
    }

    private Object[] transformar(Incidente incidente) {
        Object[] fila = {
            incidente.getCodigo(),
            incidente.getNombre(),
            incidente.getDescripcion(),
            incidente.getDetalleCaso()
        };
        return fila;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtblIncidentes = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtAvance = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtDetalle = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtActual = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        lbxBitacora = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setClosable(true);

        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        jtblIncidentes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtblIncidentes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtblIncidentesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtblIncidentes);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Bitacora"));

        jLabel1.setText("Porcentaje de avance");

        jLabel2.setText("Detalle");

        txtDetalle.setColumns(20);
        txtDetalle.setRows(5);
        jScrollPane3.setViewportView(txtDetalle);

        jLabel3.setText("Codigo de incidente:");

        txtCodigo.setEditable(false);

        jLabel4.setText("Avance Actual");

        txtActual.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtAvance, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCodigo)
                            .addComponent(txtActual))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtAvance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)))
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder("Bitacora"));

        jScrollPane2.setViewportView(lbxBitacora);

        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked

    }//GEN-LAST:event_jScrollPane1MouseClicked

    private void jtblIncidentesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtblIncidentesMouseClicked
        int fila = jtblIncidentes.rowAtPoint(evt.getPoint());
        int columna = jtblIncidentes.columnAtPoint(evt.getPoint());
        if ((fila > -1) && (columna > -1)) {
            try {
                incidenteActivo = Sesion.getDatos().getIncidenteDAO().obtenerTodos().stream().filter(inc -> {
                    if (inc.getCodigo() == null) {
                        return false;
                    }
                    return inc.getCodigo().equals((String) dtm.getValueAt(fila, 0));
                }).findFirst().orElse(null);

               

                actualizarLista();
                txtCodigo.setText(incidenteActivo.getCodigo());
            } catch (SQLException | ClassNotFoundException | DAOException ex) {
                Logger.getLogger(IfrmAprobar.class.getName()).log(Level.SEVERE, null, ex);
            }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jtblIncidentesMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Bitacora bit = new Bitacora();
        int avance = Integer.parseInt(txtAvance.getText());
        if( (avanceActual()+avance)>100){
            JOptionPane.showMessageDialog(null, "El porcentaje total de avance no puede ser mayor a 100");
            return;
        }
        
        bit.setId_incidente(incidenteActivo.getId());
        bit.setDetalle(txtDetalle.getText());
        bit.setPorcentaje(avance);
        bit.setUsuario(Sesion.getUsuario().getId());
        try {
            Sesion.getDatos().getBitacoraDAO().insertar(bit);
        } catch (SQLException | ClassNotFoundException | DAOException ex) {
            JOptionPane.showMessageDialog(this, "No se pudo guardar la bitacora");
            System.out.println(ex);
            Logger.getLogger(IfrmBitacora.class.getName()).log(Level.SEVERE, null, ex);
        }
        actualizarLista();
        if(avanceActual()==100){
            JOptionPane.showMessageDialog(this, "Felicidades has completado un incidente, estate atento a la resolucion");
            incidenteActivo.setEstado(5);
            try {
                Sesion.getDatos().getIncidenteDAO().modificar(incidenteActivo);
                limpiar();
            } catch (SQLException | ClassNotFoundException | DAOException ex) {
                JOptionPane.showMessageDialog(this, "Ha ocurrido un error al guardar el incidente");
                System.out.println(ex);
                Logger.getLogger(IfrmBitacora.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        activo=false;
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private int avanceActual(){
        int avance = 0;
        for(Bitacora b:bitacoras){
            avance += b.getPorcentaje();
        }
        return avance;
    }
    private void actualizarLista() {
        try {
            bitacoras = Sesion.getDatos().getBitacoraDAO().obtenerTodos().stream().filter(b -> {
                return b.getId_incidente() == incidenteActivo.getId();
            }).collect(Collectors.toList());
            BitacoraListModel lmodel = new BitacoraListModel();
            bitacoras.forEach(bit -> {
                lmodel.addBitacora(bit);
            });
            lbxBitacora.setModel(lmodel);
            
            txtActual.setText(avanceActual()+"%");
        } catch (SQLException | ClassNotFoundException | DAOException ex) {
            JOptionPane.showMessageDialog(this, "No se pudo cargar la lista de bitacoras");
            Logger.getLogger(IfrmBitacora.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jtblIncidentes;
    private javax.swing.JList<String> lbxBitacora;
    private javax.swing.JTextField txtActual;
    private javax.swing.JTextField txtAvance;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextArea txtDetalle;
    // End of variables declaration//GEN-END:variables

    private void limpiar() {
        cargarTabla();
        txtActual.setText("");
        txtCodigo.setText("");
        txtAvance.setText("");
        txtDetalle.setText("");
        lbxBitacora.setModel(new BitacoraListModel());
    }
}
